### ISSUE TITLE
Estado da coleta não visível

### ISSUE THREAD

**Issue by EltonCN** [H-IAAC/collect_apk#6]
Ao apertar o botão de voltar do celular enquanto uma coleta está acontecendo, não é possível descobrir qual o estado da coleta. O contador da coleta volta para o valor inicial, enquanto que os botões de "Start" e "Stop indicam que a coleta ainda está acontecendo:

Antes de apertar o botão de voltar:
![image](https://user-images.githubusercontent.com/43186596/229598103-a196cb6b-93ee-4e31-b9f5-c647dda9fa72.png)

Após apertar o botão de voltar (contador resetado e botões com coleta ativa):
![image](https://user-images.githubusercontent.com/43186596/229598345-d8b67265-16f2-44b7-8777-39f5408edc47.png)

A coleta ainda está acontecendo, e ele indica o término dela quando o temporizador termina. Apertar o botão de "Stop" também ainda funciona, parando a coleta.

Um segundo problema do estado da aplicação é que, ao terminar a coleta, o arquivo CSV da coleta terminada demora para aparecer na lista de arquivos (pelo menos para coletas de 1h~6h), e não existe nenhum indicador que algum processamento está acontecendo, parecendo que a coleta pode ter dado errado neste período.

**Comment by felipeaps89** [comment]
Corrigido na versão 1.8
