### ISSUE TITLE
Data no nome do arquivo incorreta

### ISSUE THREAD

**Issue by EltonCN** [H-IAAC/collect_apk#8]
Uma das coletas teve data no nome do arquivo incorreta.

O arquivo foi gerado com sufixo "20230406.084455", indicando que foi coletado no dia 06/04, porém ele foi coletado no dia 05/04. Os timestamps do arquivo estão corretos, todos no dia 05/04.

**Comment by felipeaps89** [comment]
O timestamp informado no nome do arquivo se refere a data de criação do arquivo, e não a data de início da coleta. 
O arquivo foi gerado somente no dia 06?

**Comment by EltonCN** [comment]
Sim, ele provavelmente foi gerado no dia 06.

Seria possível alterar para o nome do arquivo possuir a data do primeiro timestamp da coleta como sufixo?

**Comment by felipeaps89** [comment]
Alterado na versão 1.8
